server:
  port: 8080

spring:
  application:
    name: eden-generator
  redis:
   database: 0
   host: 106.14.187.183
   port: 6379
   password: slc13092271475@
   timeout: 10000 # 连接超时时间
   jedis:
     pool:
      max-active: 8 # 最大连接数
      max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
      max-idle: 5 # 最大空闲连接数
      min-idle: 0 # 最小空闲连接数
